language: swift
os: osx
osx_image: xcode9.2
before_script:
- gem install xcpretty
script:
- set -o pipefail && xcodebuild -scheme Cities -enableCodeCoverage YES clean build test | xcpretty
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'CitiesTest'
